name: company360
description: Company360 - Comprehensive Business Management App for managing employees, expenses, bookings, credit details, vehicle licenses, and more.
publish_to: "none"  # Will be removed when ready to publish
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.12.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  timezone: ^0.9.2
  workmanager: ^0.9.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/c360-background.png


